- name: installing the nginx server
  hosts: web
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: starting the nginx server
    ansible.builtin.service:
      name: nginx
      state: stopped
      #enabled: yes
