- name: printing variables paly level
  hosts: localhost
  vars:
   person: Sid # va
   job: Devops Engineer
  tasks:
  - name: printing variables 
    ansible.builtin.debug:
     msg: "Hi floks, My name is {{person}}, I am working as {{job}}.. "