- name: printing variables which is first preference
  hosts: localhost
  vars_files:
  - keep-variables.yaml
  vars_prompt:
  - name: person
    prompt: "Please enter username"
    private: false
  - name: job
    prompt: "Please enter password"
    private: true
  vars:
   person: kithu
   job: playlevel
  tasks:
  - name: printing variables
    # vars:
    #  person: Kithu
    #  job: tasklevel
    ansible.builtin.debug:
     msg: "My name is {{person}}, i am working as a {{job}}...."


# 1st Arguments 
# 2nd Task Level
# 3rd vars_files
# 4rth Prompt 
# 5th Play level
# 6th inventory 
# 7th Role