- name: command module vs shell module
  hosts: localhost
  become: yes
  tasks:
  - name: command module
    ansible.builtin.command: "echo 'Hi, this is from command module' > /tmp/command.txt "

  - name: shell module
    ansible.builtin.shell: "echo 'Hi, this is from shell module' > /tmp/shell.txt "

  
  
    # simple commands without the need of shell variables, envrironment and features like redirections, pipes, & go for command module.
    # If we need to run complex commands or scripts go for shell module.
    # Whatever works in command module, it will work in shell module, but vice versa is not true.


# Parameters → Module level
# → They explain how the module should behave or what it should do.
# (Example: path, state, mode for the file module)

# Attributes → Task level
# → They define what the task is, when or how it should run, and what to do with the result.
# (Example: name, when, register, become)